services:
  - type: web
    name: book-crud-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookproject.settings
      - key: PYTHON_VERSION
        value: 3.10
